cardir_sw(cube1, cylinder5).
cardir_sw(cube1, cube3).
cardir_sw(cube1, cube4).
cardir_sw(cube1, cylinder2).
cardir_sw(cube1, perspective_camera0).
cardir_se(cylinder5, cube3).
cardir_se(cylinder5, cube4).
cardir_se(cylinder5, cylinder2).
cardir_sw(cylinder5, perspective_camera0).
cardir_ne(cube3, cube4).
cardir_se(cube3, cylinder2).
cardir_sw(cube3, perspective_camera0).
cardir_se(cube4, cylinder2).
cardir_sw(cube4, perspective_camera0).
cardir_sw(cylinder2, perspective_camera0).