allen_b(cube2, cube3).
allen_b(cube2, cube4).
allen_b(cube2, cube5).
allen_b(cube2, cylinder1).
allen_b(cube3, cube4).
allen_b(cube3, cube5).
allen_b(cube3, cylinder1).
allen_b(cube4, cube5).
allen_b(cube4, cylinder1).
allen_b(cube5, cylinder1).