allen_d(cube2, cube3).
allen_d(cube2, cube4).
allen_d(cube2, cube5).
allen_d(cube2, cylinder1).
allen_d(cube3, cube4).
allen_d(cube3, cube5).
allen_oi(cube3, cylinder1).
allen_di(cube4, cube5).
allen_oi(cube4, cylinder1).
allen_oi(cube5, cylinder1).