allen_bi(cube2, cube3).
allen_o(cube2, cube4).
allen_bi(cube2, cube5).
allen_bi(cube2, cylinder1).
allen_b(cube3, cube4).
allen_oi(cube3, cube5).
allen_oi(cube3, cylinder1).
allen_bi(cube4, cube5).
allen_bi(cube4, cylinder1).
allen_di(cube5, cylinder1).