cardir_sw(cube2, cube3).
cardir_sw(cube2, cube4).
cardir_sw(cube2, cube5).
cardir_sw(cube2, cylinder1).
cardir_sw(cube2, perspective_camera0).
cardir_sw(cube3, cube4).
cardir_sw(cube3, cube5).
cardir_se(cube3, cylinder1).
cardir_sw(cube3, perspective_camera0).
cardir_se(cube4, cube5).
cardir_se(cube4, cylinder1).
cardir_sw(cube4, perspective_camera0).
cardir_se(cube5, cylinder1).
cardir_sw(cube5, perspective_camera0).
cardir_sw(cylinder1, perspective_camera0).