allen_di(cube1, cube2).
allen_o(cube1, cube3).
allen_oi(cube1, cylinder5).
allen_d(cube1, cylinder4).
allen_d(cube2, cube3).
allen_oi(cube2, cylinder5).
allen_d(cube2, cylinder4).
allen_oi(cube3, cylinder5).
allen_d(cube3, cylinder4).
allen_d(cylinder5, cylinder4).