cardir_nw(cube1, cube2).
cardir_se(cube1, cube3).
cardir_nw(cube1, cylinder5).
cardir_sw(cube1, perspective_camera0).
cardir_ne(cube1, cylinder4).
cardir_se(cube2, cube3).
cardir_nw(cube2, cylinder5).
cardir_sw(cube2, perspective_camera0).
cardir_se(cube2, cylinder4).
cardir_nw(cube3, cylinder5).
cardir_sw(cube3, perspective_camera0).
cardir_ne(cube3, cylinder4).
cardir_sw(cylinder5, perspective_camera0).
cardir_se(cylinder5, cylinder4).
cardir_ne(perspective_camera0, cylinder4).