ffc_r(cube2, perspective_camera0, cube4).
ffc_r(cube2, perspective_camera0, cube3).
ffc_l(cube2, perspective_camera0, cylinder1).
ffc_r(cube2, cube4, cube3).
ffc_l(cube2, cube4, cylinder1).
ffc_l(cube2, cube3, cylinder1).
ffc_l(perspective_camera0, cube4, cube3).
ffc_r(perspective_camera0, cube4, cylinder1).
ffc_r(perspective_camera0, cube3, cylinder1).
ffc_r(cube4, cube3, cylinder1).