reldistcalculus_farther(cube2, perspective_camera0, cube4).
reldistcalculus_farther(cube2, perspective_camera0, cube3).
reldistcalculus_farther(cube2, perspective_camera0, cylinder1).
reldistcalculus_closer(cube2, cube4, cube3).
reldistcalculus_closer(cube2, cube4, cylinder1).
reldistcalculus_closer(cube2, cube3, cylinder1).
reldistcalculus_closer(perspective_camera0, cube4, cube3).
reldistcalculus_farther(perspective_camera0, cube4, cylinder1).
reldistcalculus_farther(perspective_camera0, cube3, cylinder1).
reldistcalculus_closer(cube4, cube3, cylinder1).