cardir_sw(cube4, perspective_camera0).
cardir_ne(cube4, cylinder3).
cardir_se(cube4, sphere1).
cardir_ne(cube4, cylinder2).
cardir_ne(perspective_camera0, cylinder3).
cardir_ne(perspective_camera0, sphere1).
cardir_ne(perspective_camera0, cylinder2).
cardir_sw(cylinder3, sphere1).
cardir_se(cylinder3, cylinder2).
cardir_ne(sphere1, cylinder2).