reldistcalculus_farther(cube4, perspective_camera0, cylinder3).
reldistcalculus_farther(cube4, perspective_camera0, sphere1).
reldistcalculus_farther(cube4, perspective_camera0, cylinder2).
reldistcalculus_closer(cube4, cylinder3, sphere1).
reldistcalculus_closer(cube4, cylinder3, cylinder2).
reldistcalculus_closer(cube4, sphere1, cylinder2).
reldistcalculus_closer(perspective_camera0, cylinder3, sphere1).
reldistcalculus_closer(perspective_camera0, cylinder3, cylinder2).
reldistcalculus_closer(perspective_camera0, sphere1, cylinder2).
reldistcalculus_closer(cylinder3, sphere1, cylinder2).