scc_3(cube4, perspective_camera0, cylinder3).
scc_3(cube4, perspective_camera0, sphere1).
scc_3(cube4, perspective_camera0, cylinder2).
scc_1(cube4, cylinder3, sphere1).
scc_1(cube4, cylinder3, cylinder2).
scc_7(cube4, sphere1, cylinder2).
scc_1(perspective_camera0, cylinder3, sphere1).
scc_7(perspective_camera0, cylinder3, cylinder2).
scc_7(perspective_camera0, sphere1, cylinder2).
scc_7(cylinder3, sphere1, cylinder2).