allen_oi(cube1, cube2).
allen_oi(cube1, cube3).
allen_oi(cube1, cube4).
allen_oi(cube1, cube5).
allen_di(cube2, cube3).
allen_di(cube2, cube4).
allen_d(cube2, cube5).
allen_di(cube3, cube4).
allen_d(cube3, cube5).
allen_d(cube4, cube5).