allen_b(cube1, cube2).
allen_bi(cube1, cube3).
allen_b(cube1, cube4).
allen_b(cube1, cube5).
allen_bi(cube2, cube3).
allen_bi(cube2, cube4).
allen_b(cube2, cube5).
allen_b(cube3, cube4).
allen_b(cube3, cube5).
allen_b(cube4, cube5).