allen_o(cube1, cube2).
allen_oi(cube1, cube3).
allen_di(cube1, cube4).
allen_b(cube1, cube5).
allen_oi(cube2, cube3).
allen_oi(cube2, cube4).
allen_b(cube2, cube5).
allen_di(cube3, cube4).
allen_b(cube3, cube5).
allen_b(cube4, cube5).