cardir_nw(cube1, cube2).
cardir_ne(cube1, cube3).
cardir_nw(cube1, cube4).
cardir_nw(cube1, cube5).
cardir_sw(cube1, perspective_camera0).
cardir_ne(cube2, cube3).
cardir_ne(cube2, cube4).
cardir_sw(cube2, cube5).
cardir_sw(cube2, perspective_camera0).
cardir_nw(cube3, cube4).
cardir_sw(cube3, cube5).
cardir_sw(cube3, perspective_camera0).
cardir_sw(cube4, cube5).
cardir_sw(cube4, perspective_camera0).
cardir_sw(cube5, perspective_camera0).