allen_o(cube2, cylinder4).
allen_bi(cube2, cylinder3).
allen_bi(cube2, cube5).
allen_bi(cube2, cylinder1).
allen_bi(cylinder4, cylinder3).
allen_bi(cylinder4, cube5).
allen_bi(cylinder4, cylinder1).
allen_oi(cylinder3, cube5).
allen_b(cylinder3, cylinder1).
allen_b(cube5, cylinder1).