allen_oi(cube2, cylinder4).
allen_bi(cube2, cylinder3).
allen_b(cube2, cube5).
allen_oi(cube2, cylinder1).
allen_oi(cylinder4, cylinder3).
allen_b(cylinder4, cube5).
allen_di(cylinder4, cylinder1).
allen_b(cylinder3, cube5).
allen_b(cylinder3, cylinder1).
allen_bi(cube5, cylinder1).