cardir_nw(cube1, cube2).
cardir_sw(cube1, perspective_camera0).
cardir_nw(cube1, cube4).
cardir_ne(cube1, cube3).
cardir_sw(cube2, perspective_camera0).
cardir_ne(cube2, cube4).
cardir_ne(cube2, cube3).
cardir_ne(perspective_camera0, cube4).
cardir_ne(perspective_camera0, cube3).
cardir_se(cube4, cube3).