reldistcalculus_closer(cube1, cube2, perspective_camera0).
reldistcalculus_farther(cube1, cube2, cube4).
reldistcalculus_closer(cube1, cube2, cube3).
reldistcalculus_farther(cube1, perspective_camera0, cube4).
reldistcalculus_farther(cube1, perspective_camera0, cube3).
reldistcalculus_closer(cube1, cube4, cube3).
reldistcalculus_farther(cube2, perspective_camera0, cube4).
reldistcalculus_farther(cube2, perspective_camera0, cube3).
reldistcalculus_closer(cube2, cube4, cube3).
reldistcalculus_closer(perspective_camera0, cube4, cube3).