allen_bi(cube1, cube2).
allen_b(cube1, cube3).
allen_b(cube1, cube5).
allen_oi(cube1, cylinder4).
allen_b(cube2, cube3).
allen_b(cube2, cube5).
allen_b(cube2, cylinder4).
allen_bi(cube3, cube5).
allen_bi(cube3, cylinder4).
allen_bi(cube5, cylinder4).