allen_di(cube1, cube2).
allen_d(cube1, cube3).
allen_di(cube1, cube5).
allen_di(cube1, cylinder4).
allen_d(cube2, cube3).
allen_oi(cube2, cube5).
allen_d(cube2, cylinder4).
allen_di(cube3, cube5).
allen_di(cube3, cylinder4).
allen_d(cube5, cylinder4).