allen_o(cube1, cube2).
allen_b(cube1, cube3).
allen_o(cube1, cube5).
allen_b(cube1, cylinder4).
allen_di(cube2, cube3).
allen_d(cube2, cube5).
allen_b(cube2, cylinder4).
allen_d(cube3, cube5).
allen_b(cube3, cylinder4).
allen_b(cube5, cylinder4).