cardir_sw(cube1, perspective_camera0).
cardir_sw(cube1, cube4).
cardir_sw(cube1, cylinder2).
cardir_sw(cube1, cube3).
cardir_ne(perspective_camera0, cube4).
cardir_ne(perspective_camera0, cylinder2).
cardir_ne(perspective_camera0, cube3).
cardir_se(cube4, cylinder2).
cardir_sw(cube4, cube3).
cardir_nw(cylinder2, cube3).