ffc_r(cube1, perspective_camera0, cube4).
ffc_l(cube1, perspective_camera0, cylinder2).
ffc_r(cube1, perspective_camera0, cube3).
ffc_l(cube1, cube4, cylinder2).
ffc_l(cube1, cube4, cube3).
ffc_r(cube1, cylinder2, cube3).
ffc_r(perspective_camera0, cube4, cylinder2).
ffc_l(perspective_camera0, cube4, cube3).
ffc_l(perspective_camera0, cylinder2, cube3).
ffc_r(cube4, cylinder2, cube3).