reldistcalculus_farther(cube1, perspective_camera0, cube4).
reldistcalculus_farther(cube1, perspective_camera0, cylinder2).
reldistcalculus_farther(cube1, perspective_camera0, cube3).
reldistcalculus_farther(cube1, cube4, cylinder2).
reldistcalculus_closer(cube1, cube4, cube3).
reldistcalculus_closer(cube1, cylinder2, cube3).
reldistcalculus_closer(perspective_camera0, cube4, cylinder2).
reldistcalculus_farther(perspective_camera0, cube4, cube3).
reldistcalculus_farther(perspective_camera0, cylinder2, cube3).
reldistcalculus_farther(cube4, cylinder2, cube3).