cardir_ne(cube1, cube2).
cardir_sw(cube1, perspective_camera0).
cardir_sw(cube1, cube3).
cardir_ne(cube1, cylinder4).
cardir_sw(cube2, perspective_camera0).
cardir_sw(cube2, cube3).
cardir_sw(cube2, cylinder4).
cardir_ne(perspective_camera0, cube3).
cardir_ne(perspective_camera0, cylinder4).
cardir_ne(cube3, cylinder4).