ffc_l(cube1, cube2, perspective_camera0).
ffc_r(cube1, cube2, cube3).
ffc_r(cube1, cube2, cylinder4).
ffc_l(cube1, perspective_camera0, cube3).
ffc_l(cube1, perspective_camera0, cylinder4).
ffc_l(cube1, cube3, cylinder4).
ffc_l(cube2, perspective_camera0, cube3).
ffc_l(cube2, perspective_camera0, cylinder4).
ffc_l(cube2, cube3, cylinder4).
ffc_l(perspective_camera0, cube3, cylinder4).