reldistcalculus_closer(cube1, cube2, perspective_camera0).
reldistcalculus_farther(cube1, cube2, cube3).
reldistcalculus_closer(cube1, cube2, cylinder4).
reldistcalculus_farther(cube1, perspective_camera0, cube3).
reldistcalculus_farther(cube1, perspective_camera0, cylinder4).
reldistcalculus_closer(cube1, cube3, cylinder4).
reldistcalculus_farther(cube2, perspective_camera0, cube3).
reldistcalculus_farther(cube2, perspective_camera0, cylinder4).
reldistcalculus_closer(cube2, cube3, cylinder4).
reldistcalculus_farther(perspective_camera0, cube3, cylinder4).