allen_d(cube2, cylinder4).
allen_o(cube2, cylinder3).
allen_o(cube2, cube5).
allen_o(cube2, cylinder1).
allen_o(cube2, cube6).
allen_o(cylinder4, cylinder3).
allen_di(cylinder4, cube5).
allen_di(cylinder4, cylinder1).
allen_o(cylinder4, cube6).
allen_di(cylinder3, cube5).
allen_di(cylinder3, cylinder1).
allen_di(cylinder3, cube6).
allen_di(cube5, cylinder1).
allen_d(cube5, cube6).
allen_d(cylinder1, cube6).