allen_b(cube1, cylinder5).
allen_b(cube1, cube3).
allen_b(cube1, cube4).
allen_o(cube1, cylinder2).
allen_o(cube1, cylinder6).
allen_oi(cylinder5, cube3).
allen_bi(cylinder5, cube4).
allen_bi(cylinder5, cylinder2).
allen_bi(cylinder5, cylinder6).
allen_bi(cube3, cube4).
allen_bi(cube3, cylinder2).
allen_bi(cube3, cylinder6).
allen_bi(cube4, cylinder2).
allen_bi(cube4, cylinder6).
allen_o(cylinder2, cylinder6).