cardir_ne(cylinder4, cube2).
cardir_sw(cylinder4, perspective_camera0).
cardir_se(cylinder4, cylinder3).
cardir_ne(cylinder4, cylinder1).
cardir_sw(cube2, perspective_camera0).
cardir_se(cube2, cylinder3).
cardir_se(cube2, cylinder1).
cardir_ne(perspective_camera0, cylinder3).
cardir_ne(perspective_camera0, cylinder1).
cardir_nw(cylinder3, cylinder1).