ffc_r(cylinder4, cube2, perspective_camera0).
ffc_r(cylinder4, cube2, cylinder3).
ffc_r(cylinder4, cube2, cylinder1).
ffc_l(cylinder4, perspective_camera0, cylinder3).
ffc_l(cylinder4, perspective_camera0, cylinder1).
ffc_l(cylinder4, cylinder3, cylinder1).
ffc_l(cube2, perspective_camera0, cylinder3).
ffc_l(cube2, perspective_camera0, cylinder1).
ffc_l(cube2, cylinder3, cylinder1).
ffc_l(perspective_camera0, cylinder3, cylinder1).