reldistcalculus_closer(cylinder4, cube2, perspective_camera0).
reldistcalculus_closer(cylinder4, cube2, cylinder3).
reldistcalculus_closer(cylinder4, cube2, cylinder1).
reldistcalculus_farther(cylinder4, perspective_camera0, cylinder3).
reldistcalculus_farther(cylinder4, perspective_camera0, cylinder1).
reldistcalculus_farther(cylinder4, cylinder3, cylinder1).
reldistcalculus_farther(cube2, perspective_camera0, cylinder3).
reldistcalculus_farther(cube2, perspective_camera0, cylinder1).
reldistcalculus_farther(cube2, cylinder3, cylinder1).
reldistcalculus_farther(perspective_camera0, cylinder3, cylinder1).