scc_7(cylinder4, cube2, perspective_camera0).
scc_5(cylinder4, cube2, cylinder3).
scc_3(cylinder4, cube2, cylinder1).
scc_5(cylinder4, perspective_camera0, cylinder3).
scc_3(cylinder4, perspective_camera0, cylinder1).
scc_5(cylinder4, cylinder3, cylinder1).
scc_5(cube2, perspective_camera0, cylinder3).
scc_5(cube2, perspective_camera0, cylinder1).
scc_5(cube2, cylinder3, cylinder1).
scc_5(perspective_camera0, cylinder3, cylinder1).